### ISSUE TITLE
RFE - Add a "default source" configuration parameter to the config file

### ISSUE THREAD

**Issue by Victoremepunto** [RedHatInsights/bonfire#137]
It would be very helpful to have a local parameter setting to configure the default source for templates - in order to avoid using cicd_common and select, say, app-sre for instance.

The motivation here is `app-sre` seems to be a far more productive source for templates since apps seem to have working templates on app-sre and not it cicd_common.

CC @vkrizan, thanks Viliam for raising this

**Comment by bsquizz** [comment]
As of v3 the default source is 'appsre'
