### ISSUE TITLE
deploy-iqe-cji has multiple -d options

### ISSUE THREAD

**Issue by fstavela** [RedHatInsights/bonfire#166]
Using shortened `-d` option with `bonfire deploy-iqe-cji APP_NAME` can refer to both --debug-pod and --duration, which can result in a different behavior than expected.

I think we don't need a --duration option on deploy-iqe-cji command, so if we remove that option, -d can be still used as a shortened version for --debug-pod, but it may also be a good idea to find a different shortcut, so it won't be confusing.

**Comment by bsquizz** [comment]
Fixed in https://github.com/RedHatInsights/bonfire/releases/tag/v3.1.1
