### ISSUE TITLE
add --single-replicas option support when new replicas field is specified

### ISSUE THREAD

**Issue by avisiedo** [RedHatInsights/bonfire#278]
As a developer I want to update the behavior for `--single-replicas` according to the pr: https://github.com/RedHatInsights/clowder/pull/686/files that meet with:

* it deploys 1 replica when using a clowdapp resource which has minReplicas or replicas with a higher value, and --single-replica (or default value for it) is used.

**Comment by bsquizz** [comment]
Handled via #279
